version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cam-geom
    versions:
    - 0.5.0
    - 0.7.0
    - 0.8.0
  - dependency-name: nalgebra
    versions:
    - 0.24.0
    - 0.26.1
