name: build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  std-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run example
      run: cd dlt-examples && cargo run

  nostd-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ARM target
      run: rustup target add thumbv7em-none-eabihf
    - name: Build
      run: cargo build --no-default-features --target thumbv7em-none-eabihf
